import i18n from "../components/LangConfig";
let idCounter = 0;

export const ITEMS = [
  {
    id: String(idCounter++),
    imageSrc: "../../../../assets/farmfitmix.png",
    title: i18n.t("itemsArray.0.title"),
    price: 499,
    stars: Math.floor(Math.random() * 3) + 3,
    rates: Math.floor(Math.random() * 100),
    discount: "40",
    quantity: 0,
    type: i18n.t("itemsArray.0.type"),
    details: i18n.t("itemsArray.0.details"),
  },
  {
    id: String(idCounter++),
    imageSrc: "../../../../assets/wheyprotin.png",
    title: i18n.t("itemsArray.1.title"),
    price: 799,
    stars: Math.floor(Math.random() * 3) + 3,
    rates: Math.floor(Math.random() * 100),
    discount: "",
    quantity: 0,
    type: i18n.t("itemsArray.1.type"),
    details: i18n.t("itemsArray.1.details"),
  },
  {
    id: String(idCounter++),
    imageSrc: "../../../../assets/farmfitmix.png",
    title: i18n.t("itemsArray.2.title"),
    price: 499,
    stars: Math.floor(Math.random() * 3) + 3,
    rates: Math.floor(Math.random() * 100),
    discount: "",
    quantity: 0,
    type: i18n.t("itemsArray.2.type"),
    details: i18n.t("itemsArray.2.details"),
  },
  {
    id: String(idCounter++),
    imageSrc: "../../../../assets/wheyprotin.png",
    title: i18n.t("itemsArray.3.title"),
    price: 799,
    stars: Math.floor(Math.random() * 3) + 3,
    rates: Math.floor(Math.random() * 100),
    discount: "",
    quantity: 0,
    type: i18n.t("itemsArray.3.type"),
    details: i18n.t("itemsArray.3.details"),
  },
  {
    id: String(idCounter++),
    imageSrc: "../../../../assets/farmfitmix.png",
    title: i18n.t("itemsArray.4.title"),
    price: 499,
    stars: Math.floor(Math.random() * 3) + 3,
    rates: Math.floor(Math.random() * 100),
    discount: "",
    quantity: 0,
    type: i18n.t("itemsArray.4.type"),
    details: i18n.t("itemsArray.4.details"),
  },
  {
    id: String(idCounter++),
    imageSrc: "../../../../assets/wheyprotin.png",
    title: i18n.t("itemsArray.5.title"),
    price: 799,
    stars: Math.floor(Math.random() * 3) + 3,
    rates: Math.floor(Math.random() * 100),
    discount: "",
    quantity: 0,
    type: i18n.t("itemsArray.5.type"),
    details: i18n.t("itemsArray.5.details"),
  },
  {
    id: String(idCounter++),
    imageSrc: "../../../../assets/farmfitmix.png",
    title: i18n.t("itemsArray.6.title"),
    price: 499,
    stars: Math.floor(Math.random() * 3) + 3,
    rates: Math.floor(Math.random() * 100),
    discount: "",
    quantity: 0,
    type: i18n.t("itemsArray.6.type"),
    details: i18n.t("itemsArray.6.details"),
  },
];
